### ISSUE TITLE
Error in  tkz-tab.sty.

### ISSUE THREAD

**Issue by jerome-barth** [tkz-sty/tkz-tab#1]
While playing with background color, I found a bug with "fondpaille" undefined (it's the default background color) and I traced the error to tkz-tab.sty line 207.

Replacing "fondpaille" with "\cmdTAB@TTS@backgroundcolor" solved my issue.

(I did this a while ago before the files were on github.)

**Comment by davidcarlisle** [comment]
Thanks for the report

That colour name is used throughout the docs  eg

`./doc/latex/TKZdoc-tab-main.tex:\definecolor{fondpaille}{cmyk}{0,0,0.1,0}`


but as you say appears undefined here.

I set up these repositories (with Alain's permission) to do some "emergency" updates with clashes with the old etex package and current latex, I'm hoping to be able to return them to Alain once he has time,
I'll check with him if he wants me to update this from here. Your fix looks OK to me (although I don't really know the packages that well)

**Comment by davidcarlisle** [comment]
@jerome-barth  do you have a small test file ? Alain says I can update but I'm hesitant to edit the code without really knowing the package and no test case.

**Comment by jerome-barth** [comment]
OK, here is a sample, not minimal but working:
```tex
% program = LuaLaTeX -shell-escape
% encoding = UTF-8
% !Tex spellcheck = fr_FR
\documentclass[11pt,a4paper,french]{article}

\usepackage{tkz-tab} %% http://altermundus.fr/

\usetikzlibrary{arrows.meta}

\usepackage[most]{tcolorbox}
\newtcolorbox{cadrest}[1][]{%
	colback=white,
	colframe=black!85,
	left=2mm,
	right=2mm,
	top=2mm,
	bottom=2mm,
	boxsep=0mm,
	toptitle=0.7mm,
	bottomtitle=1mm,
	toptitle=1mm,
	lefttitle=5mm,
	rounded corners=all,
	leftright skip=1cm,
	skin=enhanced,
	colbacktitle=black!55,
	drop small lifted shadow=black,
	notitle,#1%
}

\newcommand*{\pinf}{{+\infty}}
\newcommand*{\minf}{{-\infty}}


%%%%%%%%%%%%%%%%%%%% Paramètres %%%%%%%%%%%%%%%%%%%%
\title{DS --- Second degré -- 1\iere{} partie}
\author{Jérôme BARTH}
\date{}

%%%%%%%%%%%%%%%%%%%% Début %%%%%%%%%%%%%%%%%%%%
\begin{document}
Dresser le tableau de variations de la fonction $f\colon x \mapsto 3(x-1)^2-2$


\begin{cadrest}[colupper=red,box align=center,width=9cm+1.8pt,center,left=-0.1pt,right=-0.1pt,top=-0.1pt,bottom=-0.1pt,boxsep=-0.1pt,colframe=red]
\begin{tikzpicture}
  \tikzset{arrow style/.style = {->, > = Stealth, shorten > = 6pt, shorten < = 6pt}}
  \tkzTabInit[nocadre]{ $x$ /1, $f(x)$ /2}{ $\minf$, $1$, $\pinf$}
  \tkzTabVar{+/ {}, -/ $-2$, +/ {}}
  \end{tikzpicture}
\end{cadrest}

\end{document}
```

**Comment by davidcarlisle** [comment]
Thanks I'll try to get an update organised this weekend,

David

**Comment by jerome-barth** [comment]
I fixed it for myself last year, and at that time I sent an email to Alain Matthes but the email address I found then was unusal so maybe he didn't get it. I don't remember exactly how I came across this issue but when I saw the color hardcoded in the .sty file while ever other color wasn't, I knew something was wrong.

**Comment by davidcarlisle** [comment]
Oh I adding \tkzTabSetup triggers the error,

**Comment by davidcarlisle** [comment]
Uploaded to ctan, thanks for the report,
